// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Contributor } from "./Contributor";
import type { ExportFormat } from "./ExportFormat";

/**
 * What the project's one book says about itself. Everything here is the
 * writer's to fill in and may stay empty; an export takes what it finds.
 */
export type Book = { 
/**
 * Generated once and never rewritten. A reader tells one book from another
 * by this, so a new one would make every earlier export a different book.
 */
identifier: string, title: string, subtitle: string, author: string, contributors: Array<Contributor>, series: string, 
/**
 * Where in the series this one falls. Text, because a book can be 1.5.
 */
seriesNumber: string, 
/**
 * A BCP 47 tag such as `en` or `pt-BR`.
 */
language: string, blurb: string, 
/**
 * Where the cover image is, relative to the project root.
 */
cover: string, publisher: string, 
/**
 * As the writer typed it: a year alone is as valid an answer as a date.
 */
publicationDate: string, isbn: string, keywords: Array<string>, copyright: string, 
/**
 * The formats ticked on the Export panel, so the next export starts from
 * the choice the last one made.
 */
exportFormats: Array<ExportFormat>, };
