// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Change } from "./Change";

/**
 * Everything that differs between two versions.
 */
export type Changes = { 
/**
 * In the newer version's order, then whatever was deleted.
 */
nodes: Array<Change>, 
/**
 * Any book detail other than the cover.
 */
book: boolean, cover: boolean, };
