// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one document or folder differs between two versions. Matched by id, so
 * a rename or a move is never read as a deletion and an addition.
 */
export type Change = { id: string, folder: boolean, 
/**
 * Its path in the older version, or none when it was added.
 */
before: string | null, 
/**
 * Its path in the newer version, or none when it was deleted.
 */
after: string | null, renamed: boolean, 
/**
 * Into another folder, not merely under a folder that was renamed.
 */
moved: boolean, 
/**
 * A document whose text differs. Never set on a folder.
 */
edited: boolean, };
