// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of a history of checkpoints.
 */
export type Checkpoint = { id: string, at: string, message: string, author: string, 
/**
 * The document's words at this checkpoint, when the list is of one document.
 */
words: number | null, };
