// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentSummary } from "./DocumentSummary";
import type { FolderKind } from "./FolderKind";

/**
 * One of a folder's children, as the overview draws it. A document gets the
 * card it has always had; a folder says what it is, how much it holds and how
 * much has been written under it.
 */
export type ChildSummary = { "node": "folder", id: string, name: string, kind: FolderKind | null, 
/**
 * How many nodes it holds directly, folders and documents alike.
 */
children: number, 
/**
 * The words in every document below it, however deep.
 */
words: number, } | { "node": "document" } & DocumentSummary;
