// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * Someone who worked on the book, and what they did.
 */
export type Contributor = { name: string, role: Role, };
