// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A document and the whole of its text, for reading the project in one go.
 * The text is `None` when the file could not be read, which the front end
 * shows rather than swallows: a document nobody could look at must not read
 * as a document with nothing in it.
 */
export type DocumentText = { text: string | null, id: string, path: string, 
/**
 * The folders it sits in, from its section down. A list rather than one
 * joined name, because the search panel draws the whole of it and the tab
 * strip only the last.
 */
trail: Array<string>, title: string, 
/**
 * Always present here, `null` when unset, so the front end has one shape
 * to read rather than a field that comes and goes.
 */
target: number | null, };
