// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A document as the sidebar shows it.
 */
export type DocumentView = { id: string, path: string, 
/**
 * The folders it sits in, from its section down. A list rather than one
 * joined name, because the search panel draws the whole of it and the tab
 * strip only the last.
 */
trail: Array<string>, title: string, 
/**
 * Always present here, `null` when unset, so the front end has one shape
 * to read rather than a field that comes and goes.
 */
target: number | null, };
