// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A document as the section overview shows it: the sidebar's view plus enough
 * of the file to tell one chapter from another without opening it.
 */
export type DocumentSummary = { words: number, excerpt: string, 
/**
 * The document's front matter block, fences and all, for the other end to
 * read its fields out of. Empty when the file has none. What a field is
 * stays defined once, in `src/frontmatter.ts`; the only thing Rust picks
 * out of a block itself is `inBook`, which the compile walk needs.
 */
front: string, modified: string | null, id: string, path: string, 
/**
 * The folders it sits in, from its section down. A list rather than one
 * joined name, because the search panel draws the whole of it and the tab
 * strip only the last.
 */
trail: Array<string>, title: string, 
/**
 * Always present here, `null` when unset, so the front end has one shape
 * to read rather than a field that comes and goes.
 */
target: number | null, };
