// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A kind of file the book can be exported as.
 */
export type ExportFormat = "markdown" | "epub" | "kepub" | "docx" | "text";
