// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much the book holds, for the Export panel to say before anything is
 * written.
 */
export type Extent = { scenes: number, words: number, };
