// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a folder inside the Manuscript is. A folder anywhere else has no kind:
 * it is a folder with a name and nothing more.
 */
export type FolderKind = "part" | "chapter" | "front-matter" | "back-matter";
