// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a folder stands against what it is aiming at: everything written under
 * it, and the target on it.
 */
export type FolderProgress = { 
/**
 * The words in every document below it, however deep, less anything in the
 * Manuscript's front or back matter.
 */
words: number, target: number | null, };
