// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Format } from "./Format";

/**
 * A format as the Welcome screen needs to describe it.
 */
export type FormatLayout = { format: Format, folders: Array<string>, available: boolean, };
