// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A version the frontend asks to keep. Every count is in words.
 */
export type Keep = { "kind": "named", name: string, } | { "kind": "session", minutes: number, written: number, removed: number, } | { "kind": "closing", written: number, removed: number, } | { "kind": "beforePuttingBack", label: string, };
