// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why Aurora kept a version.
 */
export type Kind = "named" | "session" | "closing" | "beforePuttingBack";
