// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the frontend should show on launch.
 */
export type LastProject = { "kind": "none" } | { "kind": "open", name: string, root: string, } | { "kind": "missing", name: string, root: string, };
