// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the two layers a session came from. Automatic sessions are detected
 * underneath as the writer types; a deliberate one is opened by hand and sits
 * over them. Every number Aurora shows has to say which layer it came from, so
 * the layer is recorded on the session rather than guessed at afterwards.
 */
export type Layer = "automatic" | "deliberate";
