// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a sprint was aiming at. A sprint is a deliberate session carrying one
 * of these; without it, a deliberate session runs until the writer ends it.
 */
export type Limit = { "unit": "minutes", "amount": number } | { "unit": "words", "amount": number };
