// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The six faces the manuscript can be set in. Five are vendored; the sixth is
 * whatever the desktop calls its interface font.
 */
export type ManuscriptFont = "newsreader" | "spectral" | "sourceSerif" | "plexSans" | "plexMono" | "system";
