// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderKind } from "./FolderKind";

/**
 * One entry in the project's tree as the front end reads it: [`tree::Node`]
 * with the things a node's place decides already worked out. A document
 * carries the same view every other command sends, so nothing outside Rust
 * ever takes a path apart.
 */
export type NodeView = { "node": "folder", id: string, name: string, 
/**
 * Always present, `null` outside the Manuscript, for the same reason
 * a document's target is.
 */
kind: FolderKind | null, children: Array<NodeView>, 
/**
 * The words in every document below it, however deep, less anything in
 * the Manuscript's front or back matter.
 */
words: number, 
/**
 * Whether an export takes it. The sidebar draws what is out of the
 * book faint, so this rides along with the tree rather than being
 * asked for a node at a time the way a folder's other fields are.
 *
 * Spelled out because `rename_all` on an enum renames its variants
 * and not the fields inside them.
 */
inBook: boolean, } | { "node": "document", inBook: boolean, id: string, path: string, 
/**
 * The folders it sits in, from its section down. A list rather than one
 * joined name, because the search panel draws the whole of it and the tab
 * strip only the last.
 */
trail: Array<string>, title: string, 
/**
 * Always present here, `null` when unset, so the front end has one shape
 * to read rather than a field that comes and goes.
 */
target: number | null, };
