// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A project as the frontend refers to it once it is open.
 */
export type OpenedProject = { name: string, root: string, };
