// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManuscriptFont } from "./ManuscriptFont";
import type { RightSidebarTab } from "./RightSidebarTab";
import type { SprintUnit } from "./SprintUnit";
import type { Theme } from "./Theme";

/**
 * How the writer likes to write, which follows them into every project rather
 * than belonging to any one of them.
 */
export type Preferences = { 
/**
 * Whether the bar under the document title is showing.
 */
toolbar: boolean, 
/**
 * Whether everything but the paragraph being written is dimmed.
 */
focus: boolean, 
/**
 * Whether the line the caret is on is held in place and the page moves
 * under it. Defaulted on its own, so a store written before this field
 * existed still reads rather than falling back to an empty one.
 */
typewriter: boolean, 
/**
 * Whether the list of documents is showing beside the writing. Needs a
 * default of its own: an older store has no such field, and falling back
 * to `false` would open Aurora with the sidebar gone.
 */
sidebar: boolean, 
/**
 * Whether the panel about the open document or folder is showing. Closed
 * by default: it is the writing that should have the width.
 */
rightSidebar: boolean, 
/**
 * Which of that panel's tabs is showing.
 */
rightSidebarTab: RightSidebarTab, 
/**
 * How wide the list of documents is, in pixels. Needs a default of its
 * own: a store written before this field existed would otherwise come
 * back with a sidebar no pixels wide.
 */
sidebarWidth: number, 
/**
 * How wide the panel about the open document is, in pixels. Wider than
 * the left one because its tabs have to sit side by side.
 */
rightSidebarWidth: number, 
/**
 * Whether Aurora follows the desktop's light or dark setting, or is told
 * which to use.
 */
theme: Theme, 
/**
 * The face the manuscript is set in. The chrome is not affected.
 */
manuscriptFont: ManuscriptFont, 
/**
 * What the Sprint field starts on, or none for an empty field. A writer
 * who sprints the same way every day then types nothing.
 */
defaultSprint: number | null, 
/**
 * What that sprint counts.
 */
defaultSprintUnit: SprintUnit, 
/**
 * The target a new document is given, or none for a document that is not
 * aiming at anything.
 */
defaultTarget: number | null, 
/**
 * How long a silence has to run before it closes an automatic session,
 * in minutes.
 */
idleMinutes: number, 
/**
 * Whether the titlebar shows the running session. Defaulted on: it is the
 * only place a session is visible with both sidebars hidden.
 */
sessionClock: boolean, 
/**
 * The width of the column of text, in characters.
 */
measure: number, 
/**
 * In pixels.
 */
fontSize: number, 
/**
 * A multiple of the font size, as CSS takes it.
 */
lineHeight: number, };
