// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far an export has got. Every scene read is one step towards `total` and
 * so is every file written, so `done` over `total` is how full the bar is.
 */
export type Progress = { "stage": "reading", done: number, total: number, scenes: number, } | { "stage": "writing", done: number, total: number, name: string, };
