// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A remembered project as the welcome screen shows it: what the store holds,
 * with the size of the writing counted from the files themselves.
 */
export type RecentSummary = { 
/**
 * None when the manifest could not be read, so the screen can leave the
 * count off rather than report a project as empty.
 */
words: number | null, 
/**
 * None for the same reason. The question asked before a project is
 * trashed counts what is about to go, so it needs this to be honest.
 */
documents: number | null, name: string, root: string, lastOpened: string, };
