// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A child that moved within its folder, by name as the folder now holds it.
 */
export type Reorder = { name: string, 
/**
 * The child it now comes after, or none when it is first.
 */
after: string | null, };
