// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The four things the right sidebar can be showing.
 */
export type RightSidebarTab = "synopsis" | "info" | "mentions" | "stats";
