// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What someone did on the book besides write it. Every format Aurora exports
 * wants the relationship named rather than a free line of text, so the set is
 * fixed.
 */
export type Role = "editor" | "copyEditor" | "proofreader" | "coverDesigner" | "illustrator" | "translator" | "narrator";
