// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Layer } from "./Layer";
import type { Limit } from "./Limit";
import type { Tally } from "./Tally";

/**
 * One session, as it is kept forever.
 */
export type Session = { 
/**
 * The record needs a key of its own: a deliberate session can start on the
 * same keystroke as the automatic one beneath it, so the times do not tell
 * two records apart. Minted here when a session arrives without one, since
 * inventing a UUID is not the frontend's job.
 */
id: string, layer: Layer, start: string, end: string, 
/**
 * Absent unless the session was a sprint.
 */
limit?: Limit | null, 
/**
 * Whether a sprint reached what it was aiming at. A session with no limit
 * has nothing to reach, so it writes no key.
 */
limitMet?: boolean, 
/**
 * Words added and removed across the project, accumulated from the
 * editor's per-change deltas.
 */
written: number, removed: number, 
/**
 * The project's word count at the end less its count at the start. This can
 * legitimately disagree with written less removed, because a deleted
 * document shows up here and in neither of the other two.
 */
net: number, 
/**
 * What each document gained and lost, by document id. A document nobody
 * touched is not listed.
 */
documents?: { [key in string]: Tally }, };
