// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a sprint counts. The pair the Stats tab already offers, named here so
 * the preference and the control cannot drift apart.
 */
export type SprintUnit = "words" | "minutes";
