// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one document gained and lost during a session, summed from the changes
 * the editor sees. Neither number can know about a document deleted whole.
 */
export type Tally = { written: number, removed: number, };
