// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One document in the project's trash, as the Trash view shows it.
 */
export type TrashEntry = { 
/**
 * Where it is, relative to the trash, in the same `section/file` shape a
 * document's own path uses.
 */
path: string, folder: string, 
/**
 * The title it had before it was deleted.
 */
title: string, 
/**
 * When it was deleted, or nothing at all if its name does not carry a
 * moment Aurora recognises.
 */
deleted: string | null, 
/**
 * Nothing when the entry is a document on its own. When it is a whole
 * folder, how many documents went into the trash inside it.
 */
inside: number | null, };
