// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the Versions tab lists the open document's versions or all of them.
 */
export type VersionsScope = "document" | "project";
